
package com.sgm.jqwms.wmstoilogtask;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2017-07-21T10:45:22.350+08:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SGMError", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMError/v1")
public class SGMError extends Exception {
    
    private com.saic_gm.esb.schemas.common.sgmerror.v1.SGMErrorType sgmError;

    public SGMError() {
        super();
    }
    
    public SGMError(String message) {
        super(message);
    }
    
    public SGMError(String message, Throwable cause) {
        super(message, cause);
    }

    public SGMError(String message, com.saic_gm.esb.schemas.common.sgmerror.v1.SGMErrorType sgmError) {
        super(message);
        this.sgmError = sgmError;
    }

    public SGMError(String message, com.saic_gm.esb.schemas.common.sgmerror.v1.SGMErrorType sgmError, Throwable cause) {
        super(message, cause);
        this.sgmError = sgmError;
    }

    public com.saic_gm.esb.schemas.common.sgmerror.v1.SGMErrorType getFaultInfo() {
        return this.sgmError;
    }
}
