package com.sgm.jqwms.wmstoilogtask;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2017-07-21T10:45:22.399+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.saic-gm.com/jq-wms/WmsToIlogTask/", name = "WmsToIlogTask")
@XmlSeeAlso({com.saic_gm.esb.schemas.common.sgmerror.v1.ObjectFactory.class, ObjectFactory.class, com.saic_gm.esb.schemas.common.sgmcommonheader.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WmsToIlogTask {

    @WebResult(name = "WTOIOperationResponse", targetNamespace = "http://www.saic-gm.com/jq-wms/WmsToIlogTask/", partName = "body")
    @WebMethod(operationName = "WTOIOperation", action = "http://www.saic-gm.com/jq-wms/WmsToIlogTask/WTOIOperation")
    public WTOIOperationResponse wtoiOperation(
        @WebParam(partName = "body", name = "WTOIOperation", targetNamespace = "http://www.saic-gm.com/jq-wms/WmsToIlogTask/")
        WTOIOperation body,
        @WebParam(partName = "SGMCommonHeader", mode = WebParam.Mode.INOUT, name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true)
        javax.xml.ws.Holder<com.saic_gm.esb.schemas.common.sgmcommonheader.v1.SGMCommonHeaderType> sgmCommonHeader
    ) throws SGMError;
}
