
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sgm.jqwms.wmstoilogtask;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2017-07-21T10:45:22.375+08:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WmsToIlogTask",
                      portName = "WmsToIlogTaskSOAP",
                      targetNamespace = "http://www.saic-gm.com/jq-wms/WmsToIlogTask/",
                      wsdlLocation = "file:/D:/WS_WMS_BB/Cxf/WmsToIlogTask.wsdl",
                      endpointInterface = "com.sgm.jqwms.wmstoilogtask.WmsToIlogTask")
                      
public class WmsToIlogTaskImpl implements WmsToIlogTask {

    private static final Logger LOG = Logger.getLogger(WmsToIlogTaskImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sgm.jqwms.wmstoilogtask.WmsToIlogTask#wtoiOperation(com.sgm.jqwms.wmstoilogtask.WTOIOperation  body ,)com.saic_gm.esb.schemas.common.sgmcommonheader.v1.SGMCommonHeaderType  sgmCommonHeader )*
     */
    public com.sgm.jqwms.wmstoilogtask.WTOIOperationResponse wtoiOperation(WTOIOperation body,javax.xml.ws.Holder<com.saic_gm.esb.schemas.common.sgmcommonheader.v1.SGMCommonHeaderType> sgmCommonHeader) throws SGMError    { 
        LOG.info("Executing operation wtoiOperation");
        System.out.println(body);
        System.out.println(sgmCommonHeader.value);
        try {
            com.sgm.jqwms.wmstoilogtask.WTOIOperationResponse _return = new com.sgm.jqwms.wmstoilogtask.WTOIOperationResponse();
            java.util.List<com.sgm.jqwms.wmstoilogtask.TaskResult> _returnTaskResult = new java.util.ArrayList<com.sgm.jqwms.wmstoilogtask.TaskResult>();
            com.sgm.jqwms.wmstoilogtask.TaskResult _returnTaskResultVal1 = new com.sgm.jqwms.wmstoilogtask.TaskResult();
            _returnTaskResultVal1.setWarehouseId("WarehouseId1768008132");
            _returnTaskResultVal1.setPlantId("PlantId1848472296");
            _returnTaskResultVal1.setRequestNo("RequestNo-1446225042");
            _returnTaskResultVal1.setTaskType("TaskType1002791935");
            _returnTaskResultVal1.setStatus("Status1228968903");
            _returnTaskResultVal1.setRemark("Remark-613188020");
            _returnTaskResult.add(_returnTaskResultVal1);
            _return.getTaskResult().addAll(_returnTaskResult);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SGMError("SGMError...");
    }

}
