package com.sgm.jqwms.wmstoilogtask;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2017-07-21T10:45:22.406+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "WmsToIlogTask", 
                  wsdlLocation = "file:/D:/WS_WMS_BB/Cxf/WmsToIlogTask.wsdl",
                  targetNamespace = "http://www.saic-gm.com/jq-wms/WmsToIlogTask/") 
public class WmsToIlogTask_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.saic-gm.com/jq-wms/WmsToIlogTask/", "WmsToIlogTask");
    public final static QName WmsToIlogTaskSOAP = new QName("http://www.saic-gm.com/jq-wms/WmsToIlogTask/", "WmsToIlogTaskSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WS_WMS_BB/Cxf/WmsToIlogTask.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WmsToIlogTask_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/WS_WMS_BB/Cxf/WmsToIlogTask.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WmsToIlogTask_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WmsToIlogTask_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WmsToIlogTask_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WmsToIlogTask
     */
    @WebEndpoint(name = "WmsToIlogTaskSOAP")
    public WmsToIlogTask getWmsToIlogTaskSOAP() {
        return super.getPort(WmsToIlogTaskSOAP, WmsToIlogTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmsToIlogTask
     */
    @WebEndpoint(name = "WmsToIlogTaskSOAP")
    public WmsToIlogTask getWmsToIlogTaskSOAP(WebServiceFeature... features) {
        return super.getPort(WmsToIlogTaskSOAP, WmsToIlogTask.class, features);
    }

}
